services:
  - type: web
    name: packepfecam-backend
    runtime: docker
    rootDir: packepfecam/backend
    plan: free
    healthCheckPath: /api/healthchecker
    envVars:
      - key: CLIENT_ORIGIN
        sync: false
